### ISSUE TITLE
Export failed: Type error: inputToXML is not a function

### ISSUE THREAD

**Issue by JiafengLiao** [jmoenig/Snap#3239]
I tried to save project [https://snap.berkeley.edu/project?username=cornelios207&projectname=Node%20Editor](url) on v9.0.1.
It pops"Export failed: TypeError: inputToXML is not a function" ![image](https://github.com/jmoenig/Snap/assets/15614871/133eeb4a-318b-4eec-a001-fd55bc72e599)
It didn't happened on the other project which contains only a few custom blocks.

**Comment by JiafengLiao** [comment]
Here is the xml I used.
[NodeEditor.zip](https://github.com/jmoenig/Snap/files/12180029/NodeEditor.zip)

**Comment by jmoenig** [comment]
Thanks, that's a bug! I just discovered that I forgot to put parens around a ternary operator, geez. I'll fix it asap and deploy a little patch later today. Thanks!

**Comment by jmoenig** [comment]
fixed and patched. Can you please try this again in the version I've deployed just now (v9.0.2)? It works fine for me... Thanks!

**Comment by JiafengLiao** [comment]
Hi,
Thank you for the prompt fix.
The saving and loading works fine now, yet the project [https://snap.berkeley.edu/project?username=cornelios207&projectname=Node%20Editor](https://github.com/jmoenig/Snap/issues/url) seems buggy when I tried to input the value after creation of nodes whereas it works well on v8.2.3.

**Comment by jmoenig** [comment]
if you perhaps could narrow that down somewhat more that would help me investigate, thanks!

**Comment by JiafengLiao** [comment]
Sure. Here are the reproduction steps:

1. Load the project [https://snap.berkeley.edu/project?username=cornelios207&projectname=Node%20Editor](https://github.com/jmoenig/Snap/issues/url)
2. click "green flag button" to start running.
3. Press [space] key on keyboard.
4. select "Input" - "value" to create a value node.
5. click value field on the node. 

Expected result(as in v8.2.3):
Setting value field pops up 
![image](https://github.com/jmoenig/Snap/assets/15614871/2a30d800-f65f-4dda-a377-e282ede27dfa)


Actual result(as in v9.0.2):
Here in v9.0.2, nothing shows up. No error alert.

Keep in touch if there is any ambiguity!

**Comment by jmoenig** [comment]
okay, can you help me understand a little bit more, how your project works? Where is the ASK command that pops up prompting the user to enter the value? What's the program flow here? Thanks!

**Comment by jmoenig** [comment]
I think I know what's happening and why.

**Comment by jmoenig** [comment]
in v9 evaluating an empty list input slot no longer returns "nothing" or zero or an empty text, but an empty list instead:

![empty list](https://github.com/jmoenig/Snap/assets/2596285/76486727-55a3-42bc-b6cc-b02486b94a09)

somewhere when you initialize some data for your `sockets` variable there must be such a case. Then when in your `Node input box` sprite you check whether something is of type `list` you expect it not to be one, but instead it now is an empty list instead of "nothing" or zero.

When I adjust the script to instead check whether that element is empty I think your (extremely cool and impressive, btw!) project works again in v9:

![Node Editor script pic](https://github.com/jmoenig/Snap/assets/2596285/4407a3ef-fed4-4167-804d-c2166a94fb3e)

Does this help?

**Comment by JiafengLiao** [comment]
Thank you. I will give a try and feedback if it works. It is actually a cool project from the example collections that I want to remix on.

**Comment by JiafengLiao** [comment]
I modified the block as you suggested and it is fixed! Cheers

**Comment by jmoenig** [comment]
Thanks for all the reports, the testing and the confirmation!
